### ISSUE TITLE
tests now failing after zen observable typescript

### ISSUE THREAD

**Issue by gilesbradshaw** [apollographql/apollo-link#518]
**Intended outcome:**
````
git clone https://github.com/apollographql/apollo-link.git
cd apollo-link
npm run bootstrap
npm run test
````

tests should pass

**Actual outcome:**
tests fail - seems to be failing on no default export from zenobservable

````
$ npm run test

> @ test /Users/giles/apollo-link
> lerna run -- test

lerna info version 2.9.0
lerna info versioning independent
lerna ERR! test Errored while running script in 'zen-observable-ts'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! FAIL src/__tests__/observer.ts
lerna ERR!   ● of › Basics
lerna ERR! 
lerna ERR!     TypeError: Cannot read property 'of' of undefined
lerna ERR! 
lerna ERR!        5 |     let list: Array<number> = [];
lerna ERR!        6 | 
lerna ERR!     >  7 |     return Observable.of(1, 2, 3)
lerna ERR!        8 |       .map(x => x * 2)
lerna ERR!        9 |       .forEach(x => list.push(x))
lerna ERR!       10 |       .then(() => expect(list).toEqual([2, 4, 6]));
lerna ERR!       
lerna ERR!       at Object.<anonymous> (src/__tests__/observer.ts:7:23)
lerna ERR! 
lerna ERR!   ● subscription › can close multiple times
lerna ERR! 
lerna ERR!     TypeError: Cannot read property 'of' of undefined
lerna ERR! 
lerna ERR!       14 | describe('subscription', () => {
lerna ERR!       15 |   it('can close multiple times', () => {
lerna ERR!     > 16 |     const sub = Observable.of(1).subscribe({});
lerna ERR!       17 |     sub.unsubscribe();
lerna ERR!       18 |     sub.unsubscribe();
lerna ERR!       19 |   });
lerna ERR!       
lerna ERR!       at Object.<anonymous> (src/__tests__/observer.ts:16:28)
lerna ERR! 
lerna ERR!   ● subscription › can close multiple times
lerna ERR! 
lerna ERR!     TypeError: Cannot read property 'of' of undefined
lerna ERR! 
lerna ERR!       20 | 
lerna ERR!       21 |   it('can close multiple times', () => {
lerna ERR!     > 22 |     let sub = Observable.of(1, 2).subscribe({});
lerna ERR!       23 |     sub = Observable.of(1, 2).subscribe({
lerna ERR!       24 |       next: sub.unsubscribe,
lerna ERR!       25 |     });
lerna ERR!       
lerna ERR!       at Object.<anonymous> (src/__tests__/observer.ts:22:26)
lerna ERR! 

etc...

````

**How to reproduce the issue:**
run the commands above

**Comment by evans** [comment]
Thank you for opening the issue! I'm looking into it now
