### ISSUE TITLE
authLink in ApolloLink.from causes onError to loop

### ISSUE THREAD

**Issue by StupidSexyJake** [apollographql/apollo-link#993]
**Expected Behavior**

I'm using onError to update headers as per this example: https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-error#retrying-failed-requests

Code below:

```
const client = new ApolloClient({
    ......
    link: ApolloLink.from([
        onError(({ graphQLErrors, networkError, operation, forward }) => {
            if (graphQLErrors) {
                for (let err of graphQLErrors) {
                    switch (err.extensions.code) {
                        case 'UNAUTHENTICATED':
                            const oldHeaders = operation.getContext().headers
                            console.log(oldHeaders['x-token-refresh'])
                            operation.setContext({
                                headers: {
                                    ...oldHeaders,
                                    'x-token': refreshAuthToken(oldHeaders['x-token-refresh']),
                                },
                            })
                            return forward(operation)
                    }
                }
            }
            if (networkError) {
                console.log('Network error', networkError)
            }
        }),
        authLink, 
        terminatingLink
    ]),
})
```

And the refreshAuthToken function:

```
// Refresh auth token
const refreshAuthToken = (refreshToken) => {
    client.mutate({
        mutation: REFRESH_AUTH_TOKEN,
        variables: {
            refreshToken
        },
    }).then(data => { return data.refreshAuthToken.token })
}
```

The problem is that I'm also using an auth link to get the headers. Code below:

```
// Create auth link
const authLink = setContext((_, { headers }) => {
    const tokens = getToken()
    return {
        headers: {
            ...headers,
            'x-token': tokens['x-token'] ? tokens['x-token'] : '',
            'x-token-refresh': tokens['x-token-refresh'] ? tokens['x-token-refresh'] : ''
        }
    }
})
```

Whenever I receive a 400 error response (err.extensions.code === 'UNAUTHORISED"), I want to update the header (as per the example linked above) then retry the operation again with the new header. This should result in a 200 response due to having new tokens in the header that will authorise the operation.

**Actual Behavior**
The following error message is outputted in the client console and loops over and over. This error message disappears when I remove the authLink from ApolloLink.from so I believe the error is due to a conflict with authLink fetching headers and onError updating headers.

```
// REFRESH TOKEN OUTPUTTED HERE - from console.log(oldHeaders['x-token-refresh'])
(node:20732) UnhandledPromiseRejectionWarning: Error: Network error: Response not successful: Received status code 400
    at new ApolloError (C:\Users\...\node_modules\apollo-client\bundle.umd.js:59:32)
    at Object.error (C:\Users\...\node_modules\apollo-client\bundle.umd.js:1031:52)
    at notifySubscription (C:\Users\...\node_modules\zen-observable\lib\Observable.js:134:18)
    at onNotify (C:\Users\...\node_modules\zen-observable\lib\Observable.js:165:3)
    at SubscriptionObserver.error (C:\Users\...\node_modules\zen-observable\lib\Observable.js:224:7)
    at notifySubscription (C:\Users\...\node_modules\zen-observable\lib\Observable.js:134:18)
    at onNotify (C:\Users\...\node_modules\zen-observable\lib\Observable.js:165:3)
    at SubscriptionObserver.error (C:\Users\...\node_modules\zen-observable\lib\Observable.js:224:7)
    at notifySubscription (C:\Users\...\node_modules\zen-observable\lib\Observable.js:134:18)
    at onNotify (C:\Users\...\node_modules\zen-observable\lib\Observable.js:165:3)
    at SubscriptionObserver.error (C:\Users\...\node_modules\zen-observable\lib\Observable.js:224:7)
    at C:\Users\...\node_modules\apollo-link-batch\lib\batching.js:70:61
    at Array.forEach (<anonymous>)
    at C:\Users\...\node_modules\apollo-link-batch\lib\batching.js:70:31
    at Array.forEach (<anonymous>)
    at Object.onError [as error] (C:\Users\...\node_modules\apollo-link-batch\lib\batching.js:68:20)
(node:20732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by JoviDeCroock** [comment]
Judging from the post you made in apollo-client, I can assume this is solved. Mind sharing what you did to fix it so that other people googling this can find an answer?

**Comment by StupidSexyJake** [comment]
I actually wasn't able to solve it so I'm trying different approaches. It's been over a week now of simply trying to get refresh tokens to work but every single thing I've tried has failed. I just don't get what the problem is.

**Comment by JoviDeCroock** [comment]
Well, I would suggest trying our spectrum for an answer. I personally always use implicit refresh token so that won't be of much help for yourself. I will be on the lookout to see if I can find anything but cross-posting in apollo-client and link for what seems to feel like a server issue. Won't help that much.

Since with the explanation given in apollo-client it is starting to feel like your server throws an unauthenticated on your refreshToken endpoint.

You should check your network-tab to see if you are still sending a valid token etc that will help a lot to debug this issue.

**Comment by StupidSexyJake** [comment]
I'm closing this as I believe it's a server issue. I've changed how I've approached refresh tokens and no longer have this issue.
