### ISSUE TITLE
Can't set cookies in apollo-link-error

### ISSUE THREAD

**Issue by StupidSexyJake** [apollographql/apollo-link#997]
I have the following flow setup:

- User reaches a page on the client that requires authentication to view
- Client adds auth token from cookies to req.headers and sends a query to the server to verify the auth token. Cookies are added to request headers in an auth link that is concat with the terminating link during creation of the new apollo client. See init-apollo.js code below.
- If auth token is expired, server returns an unauthenticated error
- Client receives unauthenticated error in onError of apollo-link-error.
- Client adds refresh token from cookies to req.headers and sends a mutation to the server to obtain a new auth token.
- Server returns a new auth token
- ***ISSUE: Client tries to save new token to cookies but receives an error message:
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
- Client retries original query using forward(operation)
- Original request fails again as the new auth token was not added to cookies, and therefore not sent with the request

I need to be able to set cookies in apollo-link-error. How do I achieve this?

Code below:

init-apollo.js
```
import fetch from 'isomorphic-unfetch'
// Apollo Client
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { getMainDefinition } from 'apollo-utilities'
// Apollo Link
import { ApolloLink, split, Observable } from 'apollo-link'
import { BatchHttpLink } from 'apollo-link-batch-http'
import { WebSocketLink } from 'apollo-link-ws'
import { setContext } from 'apollo-link-context'
import { onError } from 'apollo-link-error'
// Authorisation
import { setCookie } from 'nookies'
import { refreshAuthToken } from './auth'

let apolloClient = null

// Polyfill fetch() on the server (used by apollo-client)
if (!process.browser) {
    global.fetch = fetch
}

function create(initialState, { getTokens, ctx }) {
    // Create a WebSocket link
    const wsLink = process.browser ? new WebSocketLink({
        uri: `ws://<SERVER_URL>:8000/graphql`,
        options: {
            reconnect: true,
        },
    }) : null

    // Create an http link (use batch, allow cookies response from server)
    const httpLink = new BatchHttpLink({
        uri: 'http://<SERVER_URL>/api/',
        credentials: 'include'
    })

    // Split terminating link for websocket and http requests
    const terminatingLink = process.browser ? split(
        ({ query }) => {
            const { kind, operation } = getMainDefinition(query)
            return kind === 'OperationDefinition' && operation === 'subscription'
        },
        wsLink,
        httpLink,
    ) : httpLink

    // Set headers to include auth and refresh tokens
    const authLink = setContext((_, { headers }) => {
        const tokens = getTokens()
        return {
            headers: {
                ...headers,
                'x-token': tokens['x-token'] ? tokens['x-token'] : '',
                'x-token-refresh': tokens['x-token-refresh'] ? tokens['x-token-refresh'] : ''
            }
        }
    })

    // Create Apollo Client
    const client = new ApolloClient({
        connectToDevTools: process.browser,
        ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
        link: ApolloLink.from([
            authLink,
            onError(({ graphQLErrors, networkError, operation, forward }) => {
                // If network error, output message to console for debugging
                if (networkError) console.error(`[Network error]: ${networkError}`)
                // If graphQL error...
                if (graphQLErrors) {
                    // If error is due to unathenticated user request and a refresh token is available...
                    const { extensions } = graphQLErrors[0]
                    const refreshToken = getTokens()['x-token-refresh']
                    if (extensions.code === 'UNAUTHENTICATED' && refreshToken) {
                        // Create a new Observerable
                        return new Observable(async observer => {
                            // Refresh the auth token
                            await refreshAuthToken(refreshToken, client)
                                // On successful refresh...
                                .then((newToken) => {

                                    // Update cookies with new token   ::::::::: ISSUE OCCURS HERE  ::::::::::::::::::::::                          
                                    setCookie(ctx, 'x-token-test', 'test')  

                                    // Bind observable subscribers
                                    const subscriber = {
                                        next: observer.next.bind(observer),
                                        error: observer.error.bind(observer),
                                        complete: observer.complete.bind(observer)
                                    }
                                    // Retry last failed request
                                    forward(operation).subscribe(subscriber)
                                })
                                // Force user to login if refresh fails
                                .catch(error => {
                                    console.error('Error received in onError link in init-apollo')
                                    console.error(error)
                                    console.log('*****************')
                                    observer.error(error)
                                })
                        })

                    }
                }
            }),
            terminatingLink,
        ]),
        cache: new InMemoryCache().restore(initialState || {})
    })
    return client
}

export default function initApollo(initialState, options) {
    // Make sure to create a new client for every server-side request so that data isn't shared between connections
    if (!process.browser) {
        return create(initialState, options)
    }
    // Reuse client on the client-side
    if (!apolloClient) {
        apolloClient = create(initialState, options)
    }
    return apolloClient
}
```
Extract from home page that checks if the user is logged in before displaying the page
```
....
// Before page is rendered...
Index.getInitialProps = async ctx => {
    // Check if user is logged in
    const me = await checkLoggedIn(ctx)
    // If not signed in, redirect to login page
    if (!me) { redirect(ctx, '/login') }
    // Return
    return {}
}
...
```

auth.js
```
....
// Check if user is logged in
export function checkLoggedIn(ctx) {
    // Verify auth token with server (auth token sent in request headers in ./init-apollo.js)
    ctx.apolloClient.query({
        query: GET_ME,
    })
        // Return logged in user on verification success
        .then(({ data }) => {
            return { data }
        })

        // Return no user on verification failure
        .catch((error) => {
            console.error('Error in catch of checkLoggedIn() in auth.js:')
            console.error(error)
            console.log('*****************')
            return {}
        })
}

// Refresh expired auth tokens
export async function refreshAuthToken(refreshToken, client) {
    // Fetch a new auth token from the server
    await client.mutate({
        mutation: REFRESH_AUTH_TOKEN,
        variables: {
            refreshToken
        }
    })
        // On success...
        .then(data => {
            return data.data.refreshAuthToken
        })

        // Log refresh failures for debugging
        .catch(error => {
            console.error('Error received in refreshAuthToken() catch of auth.js:')
            console.error(error)
            console.log('*****************')
        })
}
....
```

Error output in console:
```
Error received in onError link in init-apollo
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at setCookie (/root/SimplyTidyAdmin/node_modules/nookies/dist/index.js:98:17)
    at /root/SimplyTidyAdmin/.next/server/static/CAhshxrRWHVF6Gzbce~pU/pages/_app.js:1273:63
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by StupidSexyJake** [comment]
So I got it working. The issue is that getInitialProps (from Next.js) only works on the server side, and I was attempting to set cookies on the client side. I used the [nookies](https://github.com/maticzav/nookies) package to set the cookies instead (as it's designed to work both server and client side in Next.js) and now it works.

**Comment by StupidSexyJake** [comment]
Actually I just reviewed my original post and it seems I was using nookies then as well. Strange. It's working now though. It may be because I wasn't returning from the refreshAuthToken function. I also deleted the existing cookie in the refreshAuthToken function before sending the mutation so that may have also solved it. I can look into it further to figure out how I fixed it if anyone has any questions, otherwise I'll just keep this closed.

**Comment by jeffreyabarrios** [comment]
> Actually I just reviewed my original post and it seems I was using nookies then as well. Strange. It's working now though. It may be because I wasn't returning from the refreshAuthToken function. I also deleted the existing cookie in the refreshAuthToken function before sending the mutation so that may have also solved it. I can look into it further to figure out how I fixed it if anyone has any questions, otherwise I'll just keep this closed.

Could you share the way you did it? I'm having the same problems.
